### ISSUE TITLE
Data for training

### ISSUE THREAD

**Issue by DucNguyenAIML** [jenngrannen/hulk-keypoints#1]
Hello. I wanna ask that how can I get data for test and train? May I need to collect pictures about the node ?
(I'm new so sorry if I've asked something stupid)

**Comment by jenngrannen** [comment]
Hi, the dataset is images of the knot configuration along with key point annotations about the first under-crossing as described in the paper. You can collect the images with any camera and label the key points manually.

**Comment by DucNguyenAIML** [comment]
> Hi, the dataset is images of the knot configuration along with key point annotations about the first under-crossing as described in the paper. You can collect the images with any camera and label the key points manually.

Thank you for your answer
